version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: snippetbox-mysql-db
    ports: 
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_DATABASE=snippetbox
      - MYSQL_ROOT_PASSWORD=snippetbox
      - MYSQL_USER=snippetbox
      - MYSQL_PASSWORD=snippetbox
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    container_name: snippetbox-DBMC
    ports:
      - 127.0.0.1:4001:8080
    environment:
      - ADMINER_DEFAULT_SERVER=snippetbox-mysql-db
      - ADMINER_DESIGN=pepa-linha-dark
    depends_on:
      - db
